### ISSUE TITLE
Proposed structure for show view

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/open-source-for-good-directory#1]
Project name
1-line description

screenshot

features

getting started
- (requirement Amazon account)
- (requirement mongoDB)

[Video Demo]

[Live Demo in Browser] 

[One click deploy]

Contributors (https://api.github.com/repos/freecodecamp/freecodecamp/contributors)

**Comment by jmcilhargey** [comment]
Awesome, thanks for the outline. I've attempted a sample based off the food bank app. Let me know if this has the style and content we're looking for. With a consistent template across the projects we should be able to parse these to create the detail layer we talked about. 

[Sample SHOW.md for food bank app](https://github.com/freeCodeCamp/open-source-for-good-directory/blob/master/SAMPLE_SHOW.md)

Appreciate any feedback or edits. Thanks!
